platform :ios, '9.0'
use_frameworks!
require_relative '../ReactNative/node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'MyTestApp' do

  # Pods for MyTestApp
  pod 'FBLazyVector', :path => "../ReactNative/node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../ReactNative/node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../ReactNative/node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../ReactNative/node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../ReactNative/node_modules/react-native/'
  pod 'React-Core', :path => '../ReactNative/node_modules/react-native/'
  pod 'React-CoreModules', :path => '../ReactNative/node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../ReactNative/node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../ReactNative/node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../ReactNative/node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../ReactNative/node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../ReactNative/node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../ReactNative/node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../ReactNative/node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../ReactNative/node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../ReactNative/node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../ReactNative/node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../ReactNative/node_modules/react-native/'

  pod 'React-cxxreact', :path => '../ReactNative/node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../ReactNative/node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../ReactNative/node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../ReactNative/node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../ReactNative/node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../ReactNative/node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../ReactNative/node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../ReactNative/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../ReactNative/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../ReactNative/node_modules/react-native/third-party-podspecs/Folly.podspec'

   pod 'react-native-event-bus', :path => '../ReactNative/react-native-event-bus'
  

  target 'MyTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end

  # This post_install hook adds the -DFB_SONARKIT_ENABLED flag to OTHER_SWIFT_FLAGS, necessary to build swift target
  post_install do |installer|
    flipper_post_install(installer)
    
    file_name = Dir.glob("*.xcodeproj")[0]
    app_project = Xcodeproj::Project.open(file_name)
    app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          if (config.build_settings['OTHER_SWIFT_FLAGS'])
            unless config.build_settings['OTHER_SWIFT_FLAGS'].include? '-DFB_SONARKIT_ENABLED'
              puts 'Adding -DFB_SONARKIT_ENABLED ...'
              swift_flags = config.build_settings['OTHER_SWIFT_FLAGS']
              if swift_flags.split.last != '-Xcc'
                config.build_settings['OTHER_SWIFT_FLAGS'] << ' -Xcc'
              end
              config.build_settings['OTHER_SWIFT_FLAGS'] << ' -DFB_SONARKIT_ENABLED'
            end
          else
            puts 'OTHER_SWIFT_FLAGS does not exist thus assigning it to `$(inherited) -Xcc -DFB_SONARKIT_ENABLED`'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xcc -DFB_SONARKIT_ENABLED'
          end
          app_project.save
        end
      end
      installer.pods_project.save
  end

end

target 'MyTestApp-tvOS' do
  # Pods for MyTestApp-tvOS

  target 'MyTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
